[package]
name = "maxminddb-uf"
version = "0.1.0"
edition = "2021"
authors = [ "Chirok <chirok11@protonmail.ch>" ]
homepage = "https://github.com/chirok11/maxminddb-uf"
description = "User-friendly MaxMindDB wrapper around `maxminddb` crate"
license = "ISC"

[dependencies]
maxminddb = "0.23.0"
